Completed prep-css-grid-classes. | Denny Min
dennymin/prep-0621-code-solutions pull request #9
Opened 2021-06-12 10:04 UTC by dennymin

![prep css grid classes screenshot](https://user-images.githubusercontent.com/85311223/121772544-cc34a800-cb2a-11eb-86e2-e1af292133c5.png)

2021-06-12 16:12 UTC, thebearingedge requested changes
Hi Denny, please update your screenshot when you have a moment, that's a screenshot of the instructions 😂

2021-06-12 16:22 UTC, dennymin commented
![prep css grid classes screenshot](https://user-images.githubusercontent.com/85311223/121782686-b1305b00-cb5f-11eb-9d57-d6d9208d456f.png)

2021-06-14 00:24 UTC, dennymin commented
![prep css grid classes screenshot](https://user-images.githubusercontent.com/85311223/121826351-26895200-cc6c-11eb-8886-96aa4332d166.png)

2021-06-14 17:29 UTC, thebearingedge approved these changes

2021-06-14 17:55 UTC, merged